// <auto-generated />
using System;
using Ijora.Storage;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ijora.RestAPI.Migrations
{
    [DbContext(typeof(IjoraServiceContext))]
    [Migration("20250107193100_DBInit")]
    partial class DBInit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Ijora.Storage.Entity.PropertyEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<long>("dd")
                        .HasColumnType("bigint");

                    b.Property<long>("ddsd")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("AKBTasks", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
